[package]
name = "bxes"
version = "0.1.0"
edition = "2021"

[dependencies]
binary_rw = "4.0.4"
num = "0.4.1"
num-derive = "0.4.1"
num-traits = "0.2.17"
rand = "0.8.5"
tempfile = "3.8.1"
uuid = "1.6.1"
variant_count = "1.1.0"
zip = "0.6.6"

[profile.release]
debug = true
